#!/usr/bin/env php
<?php
use Garden\Cli\Cli;
require "vendor/autoload.php";

$cli = new Cli();
$cli->description('OpenCore config.plist sanity checker')
    ->opt('ruleset:r', 'Rule set to check against', true, 'string')
    ->opt('markdown:m', 'Leave output in markdown format', false, 'boolean')
    ->arg('plist', 'config.plist to sanity check', true);
$args = $cli->parse($argv);

$plist = $args->getArg('plist');
$rules = $args->getOpt('ruleset');
$md = $args->getOpt('markdown');

$pd = new ParsedownExtra();

$results = function() use($plist,$rules,$md) {
               ob_start(function($buf) use($md) {
                   if($md) return $buf;
                   $pd = new ParsedownExtra();
                   return $pd->text($buf);
               });
               $oc = new OpenCorePlist($plist);
               $oc->applyRules(new Rules($rules));
               ob_end_flush();
};
$results();
